name              "chef-cookbook-djangonewproj"
maintainer        ""
maintainer_email  ""
license           ""
description       "This cookbook is intended to be used with Django Newproj Template and the corresponding Vagrantfile."
